### ISSUE TITLE
ivy-avy  does not work inside ivy-posframe

### ISSUE THREAD

**Issue by CSRaghunandan** [tumashu/ivy-posframe#6]
I get the message `zero candidates` whenever I try to invoke `ivy-avy` with ivy-posframe enabled.

**Comment by tumashu** [comment]
ivy-posframe can not work well with ivy-avy at the moment.

**Comment by CSRaghunandan** [comment]
maybe note that in README file ?

**Comment by tumashu** [comment]
Yes

**Comment by noctuid** [comment]
Do you have any idea about the cause of this issue or if it can be addressed?

**Comment by noctuid** [comment]
I can get `ivy-avy` working if I add `(with-current-buffer ivy-posframe-buffer ...)` around the collection code and use the posframe frame's selected window instead of the current window (as gotten with `frame-selected-window`). The overlays appear, and the ivy action works when selecting one (e.g. go to buffer with `ivy-switch-buffer`), but Emacs hangs afterwards. The same thing happens with `helm-posframe` and `ace-jump-helm-line`. `C-g` does not work; my computer freezes and I have to switch to another tty and kill Emacs. Maybe there is some issue with cleanup. @tumashu Do you have any idea why this is?

Also, what would be the correct way to get the posframe frame?

**Comment by noctuid** [comment]
I think the issue happens because `avy--process` selects the window when you pass it a list of candidates with windows. Doing this works for me:

```elisp
(defun ivy-posframe-avy-action (pt)
  (with-current-buffer ivy-posframe-buffer
    (ivy--done
     (substring-no-properties
      (nth (- (line-number-at-pos pt) 2) ivy--old-cands)))))

(defun ivy-posframe-avy ()
  "Jump to one of the current ivy candidates."
  (interactive)
  (unless (require 'avy nil 'noerror)
    (error "Package avy isn't installed"))
  (let* ((avy-all-windows nil)
         (avy-keys (or (cdr (assq 'ivy-avy avy-keys-alist))
                       avy-keys))
         (avy-style (or (cdr (assq 'ivy-avy
                                   avy-styles-alist))
                        avy-style))
         (window (frame-selected-window
                  (buffer-local-value 'posframe--frame
                                      (get-buffer ivy-posframe-buffer))))
         candidates)
    (with-current-buffer ivy-posframe-buffer
      (save-excursion
        (save-restriction
          (narrow-to-region
           (window-start window)
           (window-end window))
          (goto-char (point-min))
          (forward-line)
          (while (< (point) (point-max))
            (push (point) candidates)
            (forward-line)))))
    (setq avy-action #'ivy-posframe-avy-action)
    (with-selected-window window
      (avy--process
       (nreverse candidates)
       (avy--style-fn avy-style)))))
```

However, if I use this and then switch to another Emacs frame, every time I use ivy afterwards, ivy-posframe is blank/corrupted.

**Comment by noctuid** [comment]
It looks like the issue is still the window selection. If I push both the point and window, remove the `with-selected-window`, and create an alternate `avy--process` that removes the window/frame selection code and just calls `ivy-posframe-avy-action`, everything seems to work as expected.

@abo-abo Do you have any suggestions for a better way to do this?

**Comment by abo-abo** [comment]
> @abo-abo Do you have any suggestions for a better way to do this?

Not at the moment. I usually work in a single frame config, so I don't have too much experience with this. PRs with improvements for either `ivy` or `avy` are welcome.

**Comment by tumashu** [comment]
@noctuid Wow,  good job!

**Comment by noctuid** [comment]
@tumashu I can make a PR to ivy-posframe. I'm not sure that I want to use a custom version of `avy--process` though.

`ivy-avy` doesn't find any candidates by default because the ivy posframe buffer/window are not selected by default (so the text `ivy-avy` looks at is just the prompt and none of the candidate lines). The issue with `avy--process` is the window selection code. To get it to work, I just had to create a custom action and remove this:
```elisp
(avy-push-mark)
(when (and (consp res)
           (windowp (cdr res)))
  (let* ((window (cdr res))
         (frame (window-frame window)))
    (unless (equal frame (selected-frame))
      (select-frame-set-input-focus frame))
    (select-window window))
  (setq res (car res)))
```

@abo-abo Do you think it would make sense to add an optional argument to `avy--process` to prevent this code from running? Also, is `avy--process` even meant to be used externally (I know most avy packages use it but am unsure whether or not this is expected)? I'd rather not rely on internal functions in case they change (same for `avy--style-fn`, `ivy--done`, and `ivy--old-cands`).

**Comment by noctuid** [comment]
Also, I'm not very familiar with child frames myself and am not sure if there is something else that could be changed to have `ivy-avy` work as-is. The reason that `ivy-avy` doesn't find any candidates, but `ace-jump-helm-line` (for example) does seems to be that ivy uses the minibuffer, and when using ivy-posframe, the minibuffer is selected but contains none of the candidates.

Selecting the child frame's window seems to cause issues regardless of what is being displayed in it (e.g. helm or ivy). I'm not sure whether this is avoidable by altering posframe or whether you're just not supposed to select windows in child frames.
