### ISSUE TITLE
Minibuffer hiding does not work

### ISSUE THREAD

**Issue by clemera** [tumashu/ivy-posframe#62]
Hi, thanks for this great package!

After an update the minibuffer does not get hidden anymore. I have set `ivy-posframe-hide-minibuffer` to `t`. When I tried debugging this, it seems `ivy-posframe--minibuffer-setup` runs before `ivy-posframe--display` so `ivy-posframe--display-p` does not get set before running the relevant code. 

Version Info:

- ivy-20190721.1039
- ivy-posframe-20190705.2243

**Comment by smallzhan** [comment]
same issue here.

**Comment by tttuuu888** [comment]
As far as I checked, this issue occurs because `ivy-posframe--minibuffer-setup` function is called before `ivy-posframe--display` function which set `ivy-posframe--display-p` to `t`. 

I simply removed checking `ivy-posframe--display-p` from `ivy-posframe--minibuffer-setup` function and made a pull request #65.  

It seems work fine but further test will be appreciated.

Thanks.

**Comment by tttuuu888** [comment]
Oh, I just figured out @clemera  already explained all at last.. I hope @clemera wouldn't mind it :)

**Comment by tumashu** [comment]
I try to fix the problem, please try again!

**Comment by tttuuu888** [comment]
@tumashu This issue seems solved after your latest commit(https://github.com/tumashu/ivy-posframe/commit/9b084b7ae086a17a76a819e0ab3fad48bf5aeddb).
Thanks you.

**Comment by clemera** [comment]
@tumashu It's fixed now, thanks!
